language: cpp

compiler:
  - clang
  - gcc

before_install:
  - git clone https://github.com/antirez/hiredis.git && cd hiredis && make && sudo make install && sudo ldconfig && cd ..

script:
  - mkdir build
  - cd build
  - cmake ..
